name: Deploy to container apps

on:
  push:
    branches:
      - cosmos-db-integration
    paths:
      - app/**


jobs:
  basic-docker-to-azure-container-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.acr }}/fastapi:0.01 . 
      
      - name: Login to Azure
        run: |
          az login --service-principal --username ${{ secrets.CLIENT_ID }} --password ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.acr }}
      
      - name: Push to Azure Container Registry
        run: |
          docker push ${{ secrets.acr }}/fastapi:0.01

      - name: Deploy Container Instance
        run: |
          az container create \
          --resource-group cosmos-db \
          --acr-identity ${{ secrets.acr }}
          --location Poland-Central
          --name test-container
          --image ${{ secrets.acr }}/fastapi:0.01
          --os-type Linux
          --cpu 1
          --memory 1.5
