name: Build docker image

on:
  push:
    paths:
      - "app/**"

jobs:
  Login-To-Docker-Container-Images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Log in to docker image
        run: |
          docker login -U ${{ secrets.docker_login }} -P ${{ secrets.docker_personal_access_token }}
      
      - name: Build docker image
        run: docker build -t ${{ secrets.docker_login }}/fastapi-weight:latest
      
      - name: Push docker image
        run: docker push ${{ secrets.docker_login }}/fastapi-weight:latest


